const PATH={
    HOME:'/',
    SIGNUP:'/signup',
    LOGIN:'/login',
    USERSIGNUP:'/user/signup',
    SHOPKEPERSIGNUP:'/shopkeper/signup',
    USERLOGIN:'/user/login',
    SHOPKEPERLOGIN:'/shopkeper/login',
    USERPROFILE:'/user/profile',
    SHOPKEPERPROFILE:'/shopkeper/profile',
    PROFILE:'/profile',
    USERUPDATEPROFILE:'/user/update/profile',
    SHOPKEPERUPDATEPROFILE:'/shopkeper/update/profile',
    ADDMEDICINE:'/shoapkeper/addmedicine',
    ALLMEDICINEOFSINGLEADMIN:'/shoapkeper/single/allmedicine',
    UPDATEMEDICINE:'/update/medicine',//show All medicine of single user
    UPDATEMEDICINEBYADMIN:'/update/medicine/:id',
    MEDICINEDETAIL:'/detail/medicine',
    MEDICINEDETAILS:'/detail/medicine/:id',
    DYNAMICCARTROUTE:'/cart/detail',
    ADDITEMTOCART:'/cart/detail/:id',
    CARTITEMS:'/cart/items',
    BUYITEM:'/buy/item',
    BUTITEMSID:'/buy/item/:cart/:medicine',
    ORDERS:'/orders',
    ALLORDERS:'/all/orders',
    RECIPT:'/recipt', 
    RECIPTS:'/recipt/:id'
}
export default PATH